#!/bin/python3

import math
import os
import random
import re
import sys


def timeConversion(s):
    #midnight
    if s.endswith("AM") == True and s[:2]=="12":
        return s.rstrip("AM").replace("12", "00",1)
    #1am -11 am
    elif s.endswith("AM") == True and s[:2]<"12":
        return s.rstrip("AM")    
    #noon
    elif s.endswith("PM") == True and s[:2]=="12":
        return s.rstrip("PM")
    #1pm - 11 pm
    else: 
        return str(int(s[:2]) + 12) + s[2:8]

print("Input time (HH:MM:SS+PM/AM) :")
s = input()

result = timeConversion(s)

print(result)
